### ISSUE TITLE
Get CHR & SNP POS using rs ids

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [smgogarten/GWASTools#11]
I have a big list of SNP rs ids for which I would like to find the CHR no and the respective SNP position on hg38. Can you please suggest how I can use GWASTools for the same? Thanks in advance

**Comment by smgogarten** [comment]
GWASTools is not the right tool for this task. I suggest you look at [Bioconductor annotation resources](https://bioconductor.org/packages/release/BiocViews.html#___AnnotationData). There is a [support page](https://support.bioconductor.org/) where you can go for help using these resources.
