### ISSUE TITLE
how to get start and end position of the locus

### ISSUE THREAD

**Issue by ElicSY** [smgogarten/GWASTools#18]
Hi there, 

Thank you for the great effort you put into making this package! When we use gwasRtools::get_loci to get loci, is it possible to get the start and end position of each locus? If so, how can we do this? 

Best,
Shuai Yuan from Upenn

**Comment by smgogarten** [comment]
GWASTools has no such function; I think you meant to post here: https://github.com/lcpilling/lcpilling.github.io/tree/main/gwasRtools
