### ISSUE TITLE
Get NAs for Est, SE, Wald.stat and Wald.pval

### ISSUE THREAD

**Issue by ryshi06** [smgogarten/GWASTools#9]
Hi there, 

I am sorry to bother again. I have tried the assocCoxPH function with a well-built genoData, but after a long-time wait, I found the columns after Est are all NAs. Are there any possible reasons explaining this? I have got no errors or warnings during the running process.

Best,
Ruyu

**Comment by smgogarten** [comment]
That means the `coxph` function is unable to return a value for the test. It's run inside a [tryCatch](https://github.com/smgogarten/GWASTools/blob/master/R/assocCoxPH.R#L57) block in case the test fails for some variants but not for others, but in your case it seems to be failing for all variants. I'd suggest extracting genotypes for a few variants and trying to run the test directly. `coxph` might give you some more informative error messages about what's going wrong.
